apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: hashi-apps
  source:
    repoURL: https://github.com/midhundha/terraform-aws-eks-argocd-vault.git
    targetRevision: main
    path: apps/nodejs-app/k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-nodejs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true