---
apiVersion: v1
kind: Namespace
metadata:
  name: secret-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: secret-app
  name: deployment-secret-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-app
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "webapp-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/webapp"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/webapp" -}}
          export MY_SECRET="{{ .Data.data.my_secret }}"
          {{- end }}
    spec:
      containers:
      - image: midhunjoy83983/simple-secret-app:latest
        imagePullPolicy: Always
        name: secret-app
        command: ["/bin/sh", "-c"]
        args: 
          - source /vault/secrets/config && python app.py
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  namespace: secret-app
  name: service-secret-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app.kubernetes.io/name: secret-app